spring.application.name=expensestracker

spring.datasource.url=jdbc:mysql://localhost:3306/expenses_tracker
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.user.name=user
spring.security.user.password=password

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=expensestrackerapplication@gmail.com
spring.mail.password=iwup rrfe ugtk nxiq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true